# Generated by Django 3.2 on 2021-09-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreaboutuser',
            options={'managed': True, 'verbose_name': 'More About User', 'verbose_name_plural': 'More About User'},
        ),
        migrations.RemoveField(
            model_name='moreaboutuser',
            name='added_date',
        ),
    ]
