# Generated by Django 3.2 on 2021-08-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.BooleanField()),
                ('slug', models.SlugField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'managed': True,
            },
        ),
    ]
