# Generated by Django 3.2 on 2021-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loved',
            field=models.BooleanField(default=False),
        ),
    ]
