# Generated by Django 3.2 on 2021-08-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_address'),
        ('product', '0006_remove_product_loved'),
        ('order', '0007_order_loved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='loved',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
            },
        ),
    ]
