# Generated by Django 3.2 on 2021-08-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_address'),
        ('product', '0006_remove_product_loved'),
        ('order', '0008_auto_20210824_0828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customer', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='loved',
        ),
    ]
